#! /bin/sh

sxhkd &
wal -i $HOME/Pictures/Wallpapers/bspwmtwo.jpg &
synclient TapButton1=1 TapButton2=3 TapButton3=2 & 
xset -b & 
compton &
polybar top &
polybar bottom &
libinput-gestures-setup start

extmon=$(xrandr --query | grep 'DP-3')
if [[ ! $extmon == *disconnected* ]]; then
	bspc monitor 'eDP-1' -d 1 2 3
	bspc monitor 'DP-3' -d 4 5 6 7 8 9
	polybar ext_top &
	polybar ext_bottom &
else
	bspc monitor 'eDP-1' -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width         0
bspc config window_gap           9
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          21
bspc config bottom_padding       25
bspc config left_padding         0
bspc config right_padding 	 0

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
