export XCURSOR_SIZE=64
xinput --set-prop "Logitech USB Optical Mouse" "libinput Accel Speed" -0.82
echo '#1089ff' > ~/.dwm_status_color
export _JAVA_AWT_WM_NONREPARENTING=1
if [ ! -z "$(xrandr --listmonitors | grep 'DP3')" ]; then
	xrandr --output eDP1 --off
fi
picom --experimental-backends --config /home/udit/.config/picom/picom.conf &
hsetroot -cover ~/Pictures/wall.jpg
doas /bin/startcfdns &
doas /bin/turnoffgpu &
dwmbar &
exec dbus-launch dwm
