#!/bin/bash

G='\033[0;32m'
Y='\033[0;33m'
N='\033[0m'

# sudo to get user to authenticate initially
sudo echo -e "${Y}File Server Active${N}"
echo
echo -e "${G}at${N}: `pwd`"
echo
echo -e "${G}containing${N}: "
echo -e "${Y}`ls -p`${N}"
echo
echo -e "${G}ip${N}: $(ip addr | grep 192 | awk '{print $2}' | sed 's/\/.*$//')"
echo
echo -e "${G}port${N}: 80"
sudo python -m http.server 80 > /dev/null
