#!/bin/dash
# fix blank java apps
export _JAVA_AWT_WM_NONREPARENTING=1

# ask QT to use Wayland
export QT_QPA_PLATFORM=wayland

# ask Firefox to use Wayland
export MOZ_ENABLE_WAYLAND=1
export MOZ_WEBRENDER=1

# setup XDG vars for apps that might need it
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway

# fix some gtk apps launching slow
export GTK_USE_PORTAL=0

# for secrets
if [ -z "$(ps -e | grep gnome-keyring)" ]; then
  eval $(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh | sed 's/^\(.*\)/export \1/g')
fi

# hack because vscode keeps launching it's own dbus session for some reason
export WM_UKLC=yes
echo -n "$DBUS_SESSION_BUS_ADDRESS" > /tmp/.dbus_saddr

# finally, launch sway
sway
