#!/bin/bash

modprobe acpi_call
intel-undervolt apply
echo deep > /sys/power/mem_sleep
echo '1' > '/sys/module/snd_hda_intel/parameters/power_save'
echo '1500' > '/proc/sys/vm/dirty_writeback_centisecs'

if lsmod | grep -q acpi_call; then
methods="
\_SB.PCI0.PEG0.PEGP._OFF
"

for m in $methods; do
    echo -n "Trying $m: "
    echo $m > /proc/acpi/call
    result=$(cat /proc/acpi/call)
    case "$result" in
        Error*)
            echo "failed"
        ;;
        *)
            echo "works!"
        ;;
    esac
done

else
    echo "The acpi_call module is not loaded, try running 'modprobe acpi_call' or 'insmod acpi_call.ko' as root"
    exit 1
fi
