zmodload zsh/zprof

# Java
export JAVA_HOME="/usr/lib/jvm/graalvm-ce-java16-21.2.0"

# Path modifications
export PATH="/home/udit/Files/flutter/bin:$PATH"
export PATH="/home/udit/.local/bin:$PATH"
export PATH="/usr/lib/jvm/graalvm-ce-java16-21.2.0/bin:$PATH"

# Path to oh-my-zsh installation
export ZSH="/home/udit/.oh-my-zsh"

# XBPS aliases, because the commands are so fucking long
alias xbpss="xbps-query -Rs"
alias xbpsi="sudo xbps-install"
alias xbpsy="sudo xbps-install -Sy"
alias xbpsu="sudo xbps-install -Syu"

# Vim
alias vim=nvim
alias vi=nvim

# Utils
alias sudo=doas
alias icat="kitty +kitten icat"
alias code="code-oss"
alias gobrelease="go build -ldflags \"-s -w\""

# Wireguard
alias wgup="sudo wg-quick up wg0"
alias wgdown="sudo wg-quick down wg0"

# Other utils
alias supercowsay='cowsay -f $(shuf -n1 -e /usr/share/cows/*.cow) $(fortune)'
alias fixscreen="wlr-randr --output DP-3 --mode 1920x1080@60"

upload () { if [ $# = 1 -o $# = 2 ];then if [ -f "$1" ];then if [ $# = 1 ];then curl -F "file=@$1" https://file.io/ ;else if [[ "$2" =~ ^[1-9]+[wmy]$ ]];then curl -F "file=@$1" https://file.io/\?expires=$2;else echo $'Wrong expiration format.\neg. 1(w/m/y), etc.';fi;fi;else echo "file doesn't exist";fi;else echo $'usage: upload file_name.ext [expiration]\nexpiration format: 1-9(w/m/y) # (w)eeks, m(onths), (y)ear';fi }

export LANG="en_US.UTF8"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="af-magic"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Add wisely, as too many plugins slow down shell startup.
plugins=(
	zsh-autosuggestions
	zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

# Compilation flags
export ARCHFLAGS="-arch x86_64"

eval "$(zoxide init zsh)"
alias cd=z

export GPG_TTY=$(tty)
[ -f "/home/udit/.ghcup/env" ] && source "/home/udit/.ghcup/env" # ghcup-env
